CreateRide Http Function
phillstew/RideshareEventFunctions pull request #3
Opened 2023-03-09 22:20 UTC by BenBeckley

My first attempt at how the CreateRide http function. There's probably quite a few things wrongs, but this is just to get some ideas out there. 

A few initial questions  & thoughts...

Is this HttpTrigger configuration correct? 
- I imagine we want something more secure than Anonymous Authorization level.
- What http methods should it possess? Both POST and GET?

Is RideCreated the correct EventHub event to send?

What HttpStatusCode would be expected in this case?

2023-03-09 22:29 UTC, phillstew requested changes

2023-03-09 22:29 UTC, phillstew commented on RideshareEventFunctions/HttpFunctions/CreateRide.cs
> +                RideId = new Random().Next(0, 100),
So when this gets called, we will have hoped the Graphql layer will have already created the ride so we do have the ID.  You can specify another parameter in the Run() method called rideId and then we'll be able to pass in an argument in the http method with ` ?rideId=${rideId}` for the rideId

2023-03-09 22:29 UTC, phillstew commented on RideshareEventFunctions/HttpFunctions/CreateRide.cs
> +            _eventProducer.SendEvent(hubName, ride); // todo: correct Event to send?
Make sure you make this method async by making the method signature `public async Task<HttpResponseData> Run(`

and then you will want to have this line be
`await _eventProducer.SendEvent(etc...`

2023-03-09 22:29 UTC, phillstew commented on RideshareEventFunctions/HttpFunctions/CreateRide.cs
> +            response.WriteString(msg);
We probably don't need any response data, since this method is just kicking off the event. As long as we return a HttpStatusCode.200 that should be fine. 

We might want some parameter checks in the beginning to make sure the RideId is passed in though, and if it is we can return HttpStatusCode.400 I think

2023-03-10 19:50 UTC, BenBeckley commented on RideshareEventFunctions/HttpFunctions/CreateRide.cs
> +                RideId = new Random().Next(0, 100),
Ok, I understand that if GraphQL has already created the ride, then the RideId already exists, and it makes sense to pass it as a parameter.

What I don't understand is the order of events. My initial assumption was that the CreateRide Http function will be sent after a user initiates a ride in the ClientApp, effectively the starting point of the workflow. This would be before the GraphQL layer does anything.

2023-03-13 19:34 UTC, phillstew approved these changes

2023-03-13 19:38 UTC, BenBeckley commented on RideshareEventFunctions/HttpFunctions/CreateRide.cs
> +                RideId = new Random().Next(0, 100),
I have a better understanding after the architecture presentation and get how GraphQL will be triggering this http function.

2023-03-14 17:35 UTC, merged